name: Build IJKPlayer AAR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: 30.0.3

      - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: Initialize Android environment
        run: ./init-android.sh

      - name: Build FFmpeg
        run: |
          cd android/contrib
          ./compile-ffmpeg.sh clean
          ./compile-ffmpeg.sh all

      - name: Build AAR
        run: |
          cd ../../android
          ./gradlew clean assembleRelease

      - name: Upload AAR file
        uses: actions/upload-artifact@v3
        with:
          name: ijkplayer-release.aar
          path: android/ijkplayer/build/outputs/aar/ijkplayer-release.aar